swagger: '2.0'

info:
  version: '1.0.0'
  title: 'Friends'
  description: 'Microservice for creating friends between users.'
  contact:
    name: Jarrod Parkes
    email: jarrod@udacity.com
    url: http://jarrodparkes.com
  license:
    name: MIT License
    
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json